services:
  db:
    image: mariadb:10.11
    restart: unless-stopped
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
      MYSQL_DATABASE: "passbolt"
      MYSQL_USER: "passbolt"
      MYSQL_PASSWORD: "P4ssb0lt"
    volumes:
      - database_volume:/var/lib/mysql

  passbolt:
    container_name: passbolt_app  # fixed container name
    image: passbolt/passbolt:latest-ce
    # Alternatively you can use rootless:
    # image: passbolt/passbolt:latest-ce-non-root
    restart: unless-stopped
    depends_on:
      - db
    environment:
      APP_FULL_BASE_URL: https://passbolt.open-elements.cloud
      DATASOURCES_DEFAULT_HOST: "db"
      DATASOURCES_DEFAULT_USERNAME: "passbolt"
      DATASOURCES_DEFAULT_PASSWORD: "P4ssb0lt"
      DATASOURCES_DEFAULT_DATABASE: "passbolt"
    volumes:
      - gpg_volume:/etc/passbolt/gpg
      - jwt_volume:/etc/passbolt/jwt
    command:
      [
        "/usr/bin/wait-for.sh",
        "-t",
        "0",
        "db:3306",
        "--",
        "/docker-entrypoint.sh",
      ]
    ports:
      - 86:86
      - 446:446

    passbolt-init-user:
    image: passbolt/passbolt:latest-ce
    depends_on:
      - passbolt
    volumes:
      - gpg_volume:/etc/passbolt/gpg
      - jwt_volume:/etc/passbolt/jwt
      - ./passbolt_cache:/usr/share/php/passbolt/tmp  # added cache volume
    entrypoint: >
      sh -c "su -s /bin/sh -m www-data -c \"/usr/share/php/passbolt/bin/cake passbolt register_user -u ndacyayinoah@gmail.com -f Noah -l Ndacyayi -r admin\""

volumes:
  database_volume:
  gpg_volume:
  jwt_volume:
